### PR TITLE
NodeJS

### PR DESCRIPTION
**Pull request by TheTrunk**
Support:
Ubuntu 18.04, 20.04, 22.04
NodeJS 16, 18, 20
MongoDB 4.4, 5.0, 6.0, 7.0
with 22.04, 20, 7.0 being recommended

Needs more testing

### CODE REVIEW

**Comment by Cabecinha84** [comment]
tested ok both with node v18 and node v20.
Do you want to use this branch also to update packages?
image

**Comment by Cabecinha84** [comment]
build homeui is not working on node 20 (haven't tried on 18)
image

**Review by Cabecinha84 — CHANGES_REQUESTED** [review]
HomeUI is not building on node 20

**Comment by TheTrunk** [comment]
> HomeUI is not building on node 20

Ahh I think its because you are building on windows. It now depends on grep to check for what nodejs version you run. I think non of the home commands will work on windows now, I will have to figure out better way it seems

**Pull request merged**
