### PR TITLE
Vue 2.7, webpack 5

### PR DESCRIPTION
**Pull request by TheTrunk**
Updates codebase to
- webpack 5
- eslint 8
- vue 2.7

Note: This is mostly affecting HomeUI with only minor linting corrections on Flux

### CODE REVIEW

**Review by Cabecinha84 — CHANGES_REQUESTED** [review]
HomeUI doesn't load.

image

**Comment by Cabecinha84** [comment]
> HomeUI doesn't load.
> 
> image

sorry. it was using https instead of http.

**Review by Cabecinha84 — CHANGES_REQUESTED** [review]
Marketplace is not working properly. Took lots of time to fill (lots of errors on console) and when it loads click on a app doesn't do anything. And I got my cpu with 100% usage.

**Comment by XK4MiLX** [comment]
image

**Comment by Cabecinha84** [comment]
Tested all other pages and all seem to be working properly. Only marketplace is requiring some love. Cheers!

**Comment by TheTrunk** [comment]
Thank you, It is resolved :)

**Review by Cabecinha84 — CHANGES_REQUESTED** [review]
Problem persists, erros on console, and it's not possible to select (click on them) any app from marketplace.
image

**Comment by TheTrunk** [comment]
Managed to reproduce it on a server. Dev mode and running built version locally was working fine but somehow on a server it did not.
I believe it is now fixed :)

**Comment by XK4MiLX** [comment]
i dont see anymore store error :)

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Pull request merged**
