### PR TITLE
v3.17.0

### PR DESCRIPTION
**Pull request by TheTrunk**
- Maximum image size is now 2Gb instead of 500Mb
- Flux documentation (docs) has been moved to separate repository
- Additional source code documentation
- Expansion of Flux test suite
- Flux communication service is now reorganized to multiple services
- Fixes authentication for recently signed messages

### CODE REVIEW

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Comment by Cabecinha84** [comment]
@TheTrunk Many reports of error "Unauthorized. Access Denied" every time they try registering a app using home.runonflux.io.

**Comment by TheTrunk** [comment]
> @TheTrunk Many reports of error "Unauthorized. Access Denied" every time they try registering a app using home.runonflux.io.

The registrations were from runonflux.io directly. Got resovled :)

**Comment by TheTrunk** [comment]
> @TheTrunk Many reports of error "Unauthorized. Access Denied" every time they try registering a app using home.runonflux.io.

Found anothe bug that the previously adjusted authscheme was not working, added to be part of test suite as well
#20c31821bb00fbad9fd2ed29302dae6ed17bb9ae

**Pull request merged**
