### PR TITLE
Remove app from blocked

### PR DESCRIPTION
**Pull request by Roken120**
Hello,
Why my app have add to blocked app ?
Can you remove ?

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi, 
Sadly we cannot accommodate mining application. Your app is a bandwidth mining application.

**Comment by Roken120** [comment]
> Hi, Sadly we cannot accommodate mining application. Your app is a bandwidth mining application.

Hello,
Is not the bandwidth mining application is proxy server I use

**Comment by TheTrunk** [comment]
We have blocked peer2profit application  of yours https://peer2profit.io/
That is a bandwidth mining application and thus we had to step in and took it down. 
Your proxy application shall be still working well and is allowed on the network.

**Comment by Roken120** [comment]
Ok, no problem i remove from my docker image peer2profit

**Comment by Roken120** [comment]
It's done.

**Comment by Roken120** [comment]
> We have blocked peer2profit application of yours https://peer2profit.io/ That is a bandwidth mining application and thus we had to step in and took it down. Your proxy application shall be still working well and is allowed on the network.

I have remove this from my image can you remove from this list ?

**Comment by Roken120** [comment]
@TheTrunk Hello can you remove app from blocked list ?

**Comment by TheTrunk** [comment]
> @TheTrunk Hello can you remove app from blocked list ?

Hi, we currently have a policy of not removing any whitelisted and blacklisted images

**Pull request closed without merging**
