### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by adi4cyber**

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi, can you please write a description of what your app does?

**Comment by adi4cyber** [comment]
it'si lamp image

**Comment by TheTrunk** [comment]
> it's lamp image

Hi,

Can you provide more information about the application? What does it do? How can we test it?

**Comment by adi4cyber** [comment]
it's a fork from https://github.com/mattrayner/docker-lamp

Description says:

Docker-LAMP is a set of docker images that include the phusion baseimage (18.04 and 20.04 varieties), along with a LAMP stack ([Apache](http://www.apache.org/), [MySQL](https://www.mysql.com/) and [PHP](http://php.net/)) all in one handy package.

With Ubuntu 20.04 and 18.04 images on the latest-2004 and latest-1804 tags, Docker-LAMP is flexible enough to use with all of your LAMP projects.

**Pull request merged**
