### PR TITLE
v5.31.0

### PR DESCRIPTION
**Pull request by Cabecinha84**
- Fix adjusting ip on flux blockchain (deterministic list) when FluxNode ip changes;
- Prioritize app installs on correct FluxNode tiers based on app resources;
- UI improvements;
- Other small improvements.

Because of the fix, we will be enforcing this version on November 6th.

### CODE REVIEW

**Review by TheTrunk — APPROVED** [review]

**Comment by MorningLightMountain713** [comment]
What commit is ```Fix adjusting ip on flux blockchain (deterministic list) when FluxNode ip changes;```?

I can't find it. Thanks.

**Comment by TheTrunk** [comment]
> What commit is `Fix adjusting ip on flux blockchain (deterministic list) when FluxNode ip changes;`?
> 
> I can't find it. Thanks.

I believe it was caused by missing ['createconfirmationtransaction', null], line.
@Cabecinha84 can you confirm this?

**Review by MorningLightMountain713 — APPROVED** [review]

**Comment by Cabecinha84** [comment]
> > What commit is `Fix adjusting ip on flux blockchain (deterministic list) when FluxNode ip changes;`?
> > I can't find it. Thanks.
> 
> I believe it was caused by missing ['createconfirmationtransaction', null], line. @Cabecinha84 can you confirm this?

yes, that's it. FluxOs was not able to call daemon to create new confirmation transaction when new ip was detected.

**Comment by Cabecinha84** [comment]
This was the error that was happening: 2024-10-22T09:53:45.933Z         createConfirmationTransaction: {"status":"error","data":{"name":"Error","message":"Invalid Method: createconfirmationtransaction"}}

**Pull request merged**
