### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by Roken120**

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi,
Please write a complete description of what your image does and how we can test it. Or source code would be great as well.
Thank you :)

**Comment by Roken120** [comment]
Hello of course.
A socks5 proxy server in port 1080

**Comment by Roken120** [comment]
Any news ?

**Comment by TheTrunk** [comment]
There is already such a proxy whitelisted. Please be way more precise how exactly the application works, how is it different and what use do you plan for it.
We have concerns to believe the app will be turned into mining app.

**Comment by Roken120** [comment]
No only i have set proxy user and password in code.
I don't use or launch peer2profit

**Comment by TheTrunk** [comment]
Hi, your image is targetting only linux/arm64 architecture. Is this intended?
Vast majority of our network is linux/amd64 and thus we cannot guarantee high application requirements (such as request for many cores or hundreds of instances)

**Comment by Roken120** [comment]
> Hi, your image is targetting only linux/arm64 architecture. Is this intended? Vast majority of our network is linux/amd64 and thus we cannot guarantee high application requirements (such as request for many cores or hundreds of instances)

Yes for the moment i make try and i make image in my raspberry pi i will add amd64 soon

**Comment by TheTrunk** [comment]
You can also use automated docker image or github actions. You will find a lots of examples in our repositories how to use github actions for that
eg
https://github.com/RunOnFlux/folding-at-home-docker-arm/blob/main/.github/workflows/image.yml
https://github.com/RunOnFlux/chainweb-node-docker/blob/master/.github/workflows/image.yml

Just combine multiple platforms
--platform linux/amd64 .

**Comment by TheTrunk** [comment]
Please be noted that any mining is prohibited and lots of other dangerous (against good moral) content as well. We have to obey laws and so images sometimes have to get blacklisted and apps removed to comply.

**Pull request merged**
