### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by thewizard-nutu**

### CODE REVIEW

**Comment by Cabecinha84** [comment]
@thewizard-nutu can you give details about what is the app and how is going to be used? Thank you.

**Comment by thewizard-nutu** [comment]
@Cabecinha84 This is a VueJS web3 application for a NFT project with walletconnect and metamask integration.

**Comment by BIOHAZARDIQ** [comment]
Reviewing of repositories.json file is terrible (not your fault). Somebody should finally edit it in a way that each repository from that list would be on separate line.

**Comment by Cabecinha84** [comment]
Welcome to flux network!

**Comment by TheTrunk** [comment]
> Reviewing of repositories.json file is terrible (not your fault). Somebody should finally edit it in a way that each repository from that list would be on separate line.

https://github.com/RunOnFlux/flux/commit/14d128d6321ec319d65a2c2db05aa2ad8fdfd906 

💯

**Pull request merged**
