### PR TITLE
add cyberfly api docker

### PR DESCRIPTION
**Pull request by abuvanth**
update cyberfly api docker to flux

### CODE REVIEW

**Comment by abuvanth** [comment]
for testing purpose

`docker run -p 80:80 cyberfly/cyberfly-api
`

**Comment by abuvanth** [comment]
visit 

http://localhost/device/093062d0-a357-4f8a-a1cb-35f1b43c12ae?network_id=testnet04

**Comment by TheTrunk** [comment]
Hi @abuvanth 
Can you describe what cyberfly is?
Thank you

**Comment by abuvanth** [comment]
Cyberfly is a decentralized IoT platform build on kadena

**Review by TheTrunk — APPROVED** [review]

**Comment by TheTrunk** [comment]
Whitelisted

**Pull request closed without merging**
