### PR TITLE
v3.16.0

### PR DESCRIPTION
**Pull request by TheTrunk**
**Authentication improvements**
Goal is to prevent expiring of sessions while load balancer switches backend nodes. Switch of backend node causes invalidation of authentication as new node does not know of previous signed messages. New scheme allows using any signed message of Flux sign scheme that was recently signed.
- Login phrase signature is no longer stored
- instead search for loginPhrase with zelid is used
- Auth header must contain all loginPhrase, zelid and signature
- Logins now expire after 14 days
- Logins for certain permissions of user, app owner are portable from one node to another for recently valid signatures

**Other improvements**
- Refactor: .substr() is deprecated - replaced with .slice()
- Extend JSDocs for wallet section of daemonService.js
- Adds Download, Upload and ping information to UI
- Adds UPNP descriptions
- Adds constants adjustemtents for UFW and UPNP
- Fixes cache of daemon calls not being properly used

### CODE REVIEW

**Comment by Cabecinha84** [comment]
Apps ports should also be check on fluxOs startup and not only every 25 blocks.
Example, I just cleared my router UPNP settings, and rebooted all my home servers and only flux ports were open, this can cause the app to not be working properly to up to 25 blocks.

**Comment by w2vy** [comment]
I did the same kind of test (deleted ports and rebooted the node) and saw them come back right away.
I also see SetupUpnp called from startFluxFunctions which I assumed was when the system came up

**Comment by TheTrunk** [comment]
> Apps ports should also be check on fluxOs startup and not only every 25 blocks. Example, I just cleared my router UPNP settings, and rebooted all my home servers and only flux ports were open, this can cause the app to not be working properly to up to 25 blocks.

> 46ec7b2

Reflected

**Comment by TheTrunk** [comment]
> This is the error: data: '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="[http://schemas.xmlsoap.org/soap/encoding/">](http://schemas.xmlsoap.org/soap/encoding/%22%3E)<s:Body><s:Fault>s:ClientUPnPError718ConflictInMappingEntry</s:Fault></s:Body></s:Envelope>' 2022-04-21T14:50:50: }, 2022-04-21T14:50:50: isAxiosError: true, 2022-04-21T14:50:50: toJSON: [Function: toJSON] 2022-04-21T14:50:50: } 2022-04-21T14:50:50: VerifyUPNPsupport - Failed Create Mapping 2022-04-21T14:50:50: Flux port 16137 specified but UPnP failed to verify support. Shutting down.

This is coming from 
```
async function verifyUPNPsupport(apiport = config.apiport) {
```
The test in our function is 'Try to map port `apiport + 1`. So from 16137 we are testing mapping of 16138. This port is reserved for Flux but unused and so should not cause any issues testing this port. Not sure where the conflict can come from, trying to reproduce on my nodes.

**Comment by Cabecinha84** [comment]
The problem persist, but I think it's a problem that is not new.
And did not happen on all my self hosting nodes. but some I have got this after pm2 restart flux changing from master to development. Sudo reboot solves the problem.

2022-04-26T11:19:35:     request: <ref *1> ClientRequest {
2022-04-26T11:19:35:       _events: [Object: null prototype],
2022-04-26T11:19:35:       _eventsCount: 7,
2022-04-26T11:19:35:       _maxListeners: undefined,
2022-04-26T11:19:35:       outputData: [],
2022-04-26T11:19:35:       outputSize: 0,
2022-04-26T11:19:35:       writable: true,
2022-04-26T11:19:35:       destroyed: false,
2022-04-26T11:19:35:       _last: true,
2022-04-26T11:19:35:       chunkedEncoding: false,
2022-04-26T11:19:35:       shouldKeepAlive: false,
2022-04-26T11:19:35:       _defaultKeepAlive: true,
2022-04-26T11:19:35:       useChunkedEncodingByDefault: true,
2022-04-26T11:19:35:       sendDate: false,
2022-04-26T11:19:35:       _removedConnection: false,
2022-04-26T11:19:35:       _removedContLen: false,
2022-04-26T11:19:35:       _removedTE: false,
2022-04-26T11:19:35:       _contentLength: null,
2022-04-26T11:19:35:       _hasBody: true,
2022-04-26T11:19:35:       _trailer: '',
2022-04-26T11:19:35:       finished: true,
2022-04-26T11:19:35:       _headerSent: true,
2022-04-26T11:19:35:       socket: [Socket],
2022-04-26T11:19:35:       _header: 'POST /ctl/IPConn HTTP/1.1\r\n' +
2022-04-26T11:19:35:         'Accept: application/json, text/plain, */*\r\n' +
2022-04-26T11:19:35:         'Content-Type: text/xml; charset="utf-8"\r\n' +
2022-04-26T11:19:35:         'Content-Length: 595\r\n' +
2022-04-26T11:19:35:         'Connection: close\r\n' +
2022-04-26T11:19:35:         'SOAPAction: "urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"\r\n' +
2022-04-26T11:19:35:         'User-Agent: axios/0.26.1\r\n' +
2022-04-26T11:19:35:         'Host: 192.168.31.1:5351\r\n' +
2022-04-26T11:19:35:         '\r\n',
2022-04-26T11:19:35:       _keepAliveTimeout: 0,
2022-04-26T11:19:35:       _onPendingData: [Function: noopPendingOutput],
2022-04-26T11:19:35:       agent: [Agent],
2022-04-26T11:19:35:       socketPath: undefined,
2022-04-26T11:19:35:       method: 'POST',
2022-04-26T11:19:35:       maxHeaderSize: undefined,
2022-04-26T11:19:35:       insecureHTTPParser: undefined,
2022-04-26T11:19:35:       path: '/ctl/IPConn',
2022-04-26T11:19:35:       _ended: true,
2022-04-26T11:19:35:       res: [IncomingMessage],
2022-04-26T11:19:35:       aborted: false,
2022-04-26T11:19:35:       timeoutCb: null,
2022-04-26T11:19:35:       upgradeOrConnect: false,
2022-04-26T11:19:35:       parser: null,
2022-04-26T11:19:35:       maxHeadersCount: null,
2022-04-26T11:19:35:       reusedSocket: false,
2022-04-26T11:19:35:       host: '192.168.31.1',
2022-04-26T11:19:35:       protocol: 'http:',
2022-04-26T11:19:35:       _redirectable: [Writable],
2022-04-26T11:19:35:       [Symbol(kCapture)]: false,
2022-04-26T11:19:35:       [Symbol(kNeedDrain)]: false,
2022-04-26T11:19:35:       [Symbol(corked)]: 0,
2022-04-26T11:19:35:       [Symbol(kOutHeaders)]: [Object: null prototype]
2022-04-26T11:19:35:     },
2022-04-26T11:19:35:     data: '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>718</errorCode><errorDescription>ConflictInMappingEntry</errorDescription></UPnPError></detail></s:Fault></s:Body></s:Envelope>'
2022-04-26T11:19:35:   },
2022-04-26T11:19:35:   isAxiosError: true,
2022-04-26T11:19:35:   toJSON: [Function: toJSON]
2022-04-26T11:19:35: }
2022-04-26T11:19:35: VerifyUPNPsupport - Failed Create Mapping
2022-04-26T11:19:35: Flux port 16157 specified but UPnP failed to verify support. Shutting down.
2022-04-26T11:19:35: [nodemon] clean exit - waiting for changes before restart

**Review by Cabecinha84 — APPROVED** [review]
Ack. Release should be scheduled and announced. If people with multiportnodes needs to reboot or do something because something went wrong, it's good they know when it will happen. Making a cumulus go offline can be painfull.

**Comment by TheTrunk** [comment]
I see, My guess is that since we are now adding description, it is a
conflicting change. We can resolve it by removing the mapped port and
mapping it again but I let's look for better solution

**Pull request merged**
