### PR TITLE
Update repositories.json

### PR DESCRIPTION
**Pull request by fegauthier**
I want to add my docker container to the verified list.

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi, can you please describe what your application does?

**Comment by fegauthier** [comment]
@TheTrunk It's a NodeJS app that fetch and parse some IPTV schedule data. The app provide an endpoint to retrieve these data.

**Comment by TheTrunk** [comment]
@fegauthier Hi, can you be more specific? As we cannot allow streaming of copyrighted content for example.
Is the app running somewhere? Do you have source available?

**Comment by fegauthier** [comment]
@TheTrunk The app is currently running at https://epg.globomine.ca/diablo . I wanted to test FluxOS, but if it's not allowed, let me know.

**Comment by TheTrunk** [comment]
I believe it is fine as I do not see any prohibited content on the above link

**Pull request merged**
