### PR TITLE
v5.28.1

### PR DESCRIPTION
**Pull request by TheTrunk**
- Fix application directory creation and permission assignment

### CODE REVIEW

**Review by MorningLightMountain713 — APPROVED** [review]
Looks good

**Comment by Cabecinha84** [comment]
Something not good, my nodes are getting this error since the commit:
Failed: Error on FluxOs response - Unavailability to mount applications volumes. Impossible to run applications.

**Comment by Cabecinha84** [comment]
all my development nodes are going down

**Review by Cabecinha84 — APPROVED** [review]
ack

**Comment by Cabecinha84** [comment]
mount test is now passing and apps are now installing without errors.

**Pull request merged**
