### PR TITLE
Terminal

### PR DESCRIPTION
**Pull request by XK4MiLX**
- redesigned Execute Commands section
- added  Browser-based Interactive Terminal

### CODE REVIEW

**Comment by TheTrunk** [comment]
This is all ready right?

**Comment by XK4MiLX** [comment]
> This is all ready right?

yes

**Review by Cabecinha84 — APPROVED** [review]
Ack. Great job!

**Comment by cryptofries-io** [comment]
Impressive redesign of the execute commands section, @XK4MiLX! It's more intuitive now! 👍
High code coverage shown in the Codecov bot report which is essential for robust ecosystem!

**Pull request merged**
