### PR TITLE
Update repositories.json | Fix HSD IP issue

### PR DESCRIPTION
**Pull request by FliKites**

### CODE REVIEW

**Comment by Cabecinha84** [comment]
Can you give details about the app and how will you use it?
Thank you.

**Comment by FliKites** [comment]
Hi. This latest pull request is just an updated version of this pull request. https://github.com/RunOnFlux/flux/pull/589

You'll see that the image is the same "hsd"


I had a different developer add the needed fix in order for the image to work properly on Flux. 

This image is a full node for https://handshake.org, it will be used to provider resources to the Handshake Blockchain.

**Comment by FliKites** [comment]
Please look at the comments from the pull request I linked to, you will notice that the issue was regarding getting the IP of the node. Trunks suggested the edit.

**Review by FliKites — COMMENTED** [review]
Forgot to add first part of image tag

**Pull request merged**
