### PR TITLE
Add STECTIX test repo

### PR DESCRIPTION
**Pull request by arkitoure**

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi, Thank you for a PR. Can you please explain what your image does? Do you have source code available? There are already helloworld images whitelisted btw.

**Comment by arkitoure** [comment]
> Hi, Thank you for a PR. Can you please explain what your image does? Do you have source code available? There are already helloworld images whitelisted btw.

Hello...just a quick personal test of ngnix to kickoff.

**Comment by TheTrunk** [comment]
Hi @arkitoure 
I see that the target architecture is only arm64 - this is sadly a very small part of Flux network and so it may take longer for an application to spawn on the network. I highly suggest updating the image to also support amd64 architecture

**Comment by arkitoure** [comment]
> Hi @arkitoure I see that the target architecture is only arm64 - this is sadly a very small part of Flux network and so it may take longer for an application to spawn on the network. I highly suggest updating the image to also support amd64 architecture


Sure Ill rebuild it asap!

**Pull request closed without merging**
