### PR TITLE
Feature: FluxDrive Backup/Restore

### PR DESCRIPTION
**Pull request by alihm**
This pull request adds UI communication to the FluxDrive middleware, enabling backup storage and retrieval from FluxDrive. Additionally, some changes have been made to the download function in IOUtils.js to support large files and handle download failures.

### CODE REVIEW

**Review by Cabecinha84 — CHANGES_REQUESTED** [review]
When the backup is finished, let's have all files pre selected or people will not even know the possibility to upload to flux drive exist, unless they click on the file. This way seems like only download option exists. Makes sense?
image

**Comment by Cabecinha84** [comment]
On my screen, with 100% zoom, I don't see the site options...
image

**Comment by Cabecinha84** [comment]
image
Continues to not work...

**Comment by Cabecinha84** [comment]
When I download the file from the drive I get a .gz file, where inside there is another zip file.
image
And inside that zip file it's the real content:
image
And when I download the backup file directly from fluxOs, I get a tar.gz with the content expected inside:
image

**Comment by Cabecinha84** [comment]
Can we have a loading bar here when uploading to fluxdrive?
image

**Comment by Cabecinha84** [comment]
Seems like even with the 3 retries it still fails...
image

**Comment by Cabecinha84** [comment]
> Seems like even with the 3 retries it still fails... image

Pressed already 10 times the restore and always fails on download task.

**Comment by alihm** [comment]
> When the backup is finished, let's have all files pre selected or people will not even know the possibility to upload to flux drive exist, unless they click on the file. This way seems like only download option exists. Makes sense? image

Improved visuals and added text so users know they need to select components to upload

**Comment by alihm** [comment]
> On my screen, with 100% zoom, I don't see the site options... image
image

added ellipses for long links. urls are also clickable now.

**Comment by Cabecinha84** [comment]
image
Instead of the message bellow the table I would prefer to see all elements of the table pre selected.

**Comment by Cabecinha84** [comment]
Or leave the message, but put the part bellow showing even if nothing is selected, and the button to upload to fluxdrive only getting enable after you select some component.
image

**Comment by Cabecinha84** [comment]
the restore process, needs to be adjusted to the screen.
Things only show up if I resize the browser to 90%, this is how it shows up if it is on 100%:
image

**Comment by Cabecinha84** [comment]
Can we add a information on mouse ouver on FluxDrive button, explaining that there is a limit of 10GB max that can be used for free for each application and the backups done on this way are only available to download from FluxOS UI on restore page.
image

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Pull request merged**
