### PR TITLE
Whitelist Docker Repo

### PR DESCRIPTION
**Pull request by henri228**
Hi, as mentioned on your website, I would like to whitelist my docker repo to be able to deploy

henri228/noderank

thanks

### CODE REVIEW

**Comment by Cabecinha84** [comment]
This PR whitelist almost 50 repos, can you explain what are you aiming?
What is your app?
How can we test it?

**Comment by henri228** [comment]
Hi,
Thank you for your reply.
Unless I'm mistaken, I don't understand why you are talking about 50 repos?
I wanted to whitelist this repo only: https://hub.docker.com/r/henri228/noderank which a very simple HTML page... 
The objective is to test the full process of deploying.
Later, I would like to deploy a more developed app.

Thanks for your return,

**Comment by Cabecinha84** [comment]
Hi Henri, tahnk you for your reply.
Here on github on the PR if you press Files changed tab, you will see what I am talking about. All green lines are marked as lines that are being added to the main with your PR.
I strongly suggest you to close this PR. Delete Flux from your workspace, make a new fork, commit your change and make a new clean PR.
Cheers!

**Comment by TheTrunk** [comment]
Whitelisted manually.

**Pull request closed without merging**
