### PR TITLE
added repository kuboloitte/noderank:latest

### PR DESCRIPTION
**Pull request by suryapratap1**
Trying to deploy website on flux node for that i have created repository on docker and added a docker image named as docker pull kuboloitte/noderank:latest

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi,
Can you please write a little description onto what your app does and how can we test it?

**Comment by TheTrunk** [comment]
Your image seems to be private, Flux can only run public images.

**Comment by suryapratap1** [comment]
> Your image seems to be private, Flux can only run public images.

Thanks let me do this

**Comment by suryapratap1** [comment]
> Hi, Can you please write a little description onto what your app does and how can we test it?

Sure thing, I will in public image PR. Thanks for such fast support

**Comment by TheTrunk** [comment]
Image is still private.

**Pull request closed without merging**
