### PR TITLE
Whitelist the docker hub for coolbuster999

### PR DESCRIPTION
**Pull request by CoolBuster999**
trying to deploy and test my first Flux dapp!

### CODE REVIEW

**Comment by TheTrunk** [comment]
Hi, what would you like to deploy on Flux?
Be aware that mining of any sort including bandwidth mining is strictly prohibited.

**Comment by CoolBuster999** [comment]
> Hi, what would you like to deploy on Flux? Be aware that mining of any sort including bandwidth mining is strictly prohibited.

Hello. I wanted to try and make a dero node. Would this violate the rule surrounding mining?

**Comment by 0xJohnny21** [comment]
> Hi, what would you like to deploy on Flux? Be aware that mining of any sort including bandwidth mining is strictly prohibited.

Looks like cpu mining
checkout this https://hub.docker.com/layers/coolbuster999/dero/latest/images/sha256-4c671c65dcfafc2e3d81dff361fb715e02d1f8b478f5f8bce24a7c5a1e827956

image uses https://github.com/Intergalactic-Mining/Uranus/releases/tag/0.0.3.1

**Comment by CoolBuster999** [comment]
I am new to the process of deploying through Docker Hub so I was trying to test that using Flux. I was going to try a CPU miner and a node. The first thing Trunk said was mining of any sort wasn't allowed. I did not know that going into this. I would still like to be able to deploy a Dero node, if possible, unless doing that still relates to that rule.

**Comment by TheTrunk** [comment]
Sounds good :+1:

**Pull request merged**
